name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Smoke test (quick)
        run: |
          python main.py --tickers SPY QQQ TLT GLD --start 2020-01-01 --end 2020-06-30 --states 3
          pytest -q || true
